server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sealmic?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  flyway:
    baseline-on-migrate: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      write_null_map_values: false
    deserialization:
      accept_single_value_as_array: true
    default-property-inclusion: non_null

## JWT 鉴权配置
jwt:
  secret: "ay9pL#$SealMic"
  ttlInMilliSec: -1

## 融云 IM 配置
im:
  appKey: xxxxxx
  secret: xxxxxx
  host: http://api-cn.ronghub.com

## 融云 SMS 配置
sms:
  appKey: xxxxxx
  secret: xxxxxx
  host: http://api.sms.ronghub.com
  templateId: 2hgGM2zw4_XbnbYdpiZAmn #登录短信模块 Id

## Redis 连接配置
redis:
  host: 127.0.0.1
  port: 6379
  pass:
  maxIdle: 100
  maxTotal: 300
  testOnBorrow: true

## SealMic 应用配置
sealmic:
  domain: http://127.0.0.1:8080 # SealMic Server 地址，协议://域名:端口
  login:
    sms_verify: false #登录是否校验短信验证码
  mic:
    transfer_host_expire: 300 #主持人转让信息过期时间，单位秒
    takeover_host_expire: 300 #接管主持人信息过期时间，单位秒

## 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    cn.rongcloud: INFO
  file:
    max-history: 8
    name: logs/sealmic.log
    max-size: 100MB
  pattern:
    rolling-file-name: logs/sealmic.%d{yyyy-MM-dd}.%i.gz