-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 10:52:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sealmic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sealmic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sealmic` DEFAULT CHARACTER SET utf8 ;
USE `sealmic` ;

-- -----------------------------------------------------
-- Table `sealmic`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmic`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NULL,
  `portrait` VARCHAR(128) NULL,
  `create_dt` DATETIME NULL,
  `update_dt` DATETIME NULL,
  `name_id` INT NOT NULL DEFAULT 0 COMMENT '随机名字 id，客户端根据 id 取名字',
  `portrait_id` INT NOT NULL DEFAULT 0,
  `device_uid` VARCHAR(64) NOT NULL COMMENT '设备 id',
  UNIQUE INDEX `user_idx` (`uid` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealmic`.`t_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmic`.`t_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) CHARACTER SET 'utf8' NULL,
  `bg_id` INT NOT NULL DEFAULT 0 COMMENT '随机背景 id，客户端根据 id 取图片',
  `create_dt` DATETIME NULL,
  `subject` VARCHAR(128) NOT NULL COMMENT '房间主题',
  `type` INT NOT NULL COMMENT '房间类型',
  `creator_uid` VARCHAR(64) NULL COMMENT '创建人',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `group_idx` (`rid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealmic`.`t_room_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmic`.`t_room_member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) NOT NULL COMMENT 'room id',
  `uid` VARCHAR(64) NOT NULL COMMENT 'user id',
  `join_dt` DATETIME NULL,
  `role` INT NULL,
  UNIQUE INDEX `user_group_idx` (`rid` ASC, `uid` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sealmic`.`t_room_mic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sealmic`.`t_room_mic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rid` VARCHAR(64) NOT NULL,
  `uid` VARCHAR(64) NULL,
  `position` INT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rid_pos_idx` (`rid` ASC, `position` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
